### ISSUE TITLE
Insufficient checks

### ISSUE THREAD

**Issue by iiroj** [abranhe/check-camelcase#1]
Hello,

this library does not have sufficient checks for determining true camelCase strings. I've added test cases for some examples that are checked incorrectly here:
https://github.com/iiroj/check-camelcase/commit/a09ee051a32897fe9184589de338416a32733840

**Comment by abranhe** [comment]
Thank you so much for your contribution. 💪 You rock @iiroj. 

You can feel free to open a new pull request adding those tests.
